config/routes.rb
Rails.application.routes.draw do
	root 'projects#more'
  resources :users
  resources :tasks
  resources :projects
  get 'more_info', to: 'projects#more'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :tasks, dependent: :destroy
	validates :name, :summary, presence: true,
	length: { minimum: 5 }
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project
	has_many :users, dependent: :destroy
	validates :title, :description, presence: true,
	length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def more
    @tasks = Task.all
    @projects = Project.all
    @users = User.all
  end

  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to more_info_url, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to more_info_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :summary, :start_date, :end_date)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to more_info_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :status, :project_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to more_info_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :admin, :task_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <%= link_to 'New Project', new_project_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Task', new_task_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'New User', new_user_path %>
      </li>
    </ul>

    <%= yield %>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br>
    <%= form.label :name %>  <br>
    <%= form.text_field :name %> <br>
  </div>

  <div class="field">
    <br>
    <%= form.label :summary %>  <br>
    <%= form.text_area :summary %> <br>
  </div>

  <div class="field">
    <br>
    <%= form.label :start_date %>  <br>
    <%= form.date_select :start_date %> <br>
  </div>

  <div class="field">
    <br>
    <%= form.label :end_date %> <br>
    <%= form.date_select :end_date %> <br>
  </div>

  <div class="actions">
    <br>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', more_info_url %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Summary</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.summary %></td>
        <td><%= project.start_date %></td>
        <td><%= project.end_date %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/more.html.erb
<h1>Ruby on rails</h1>  
<br>  
<h2>Projects</h2>
<table>  
  <thead>  
    <tr>  
      <th>Project id</th>  
      <th>Name of project</th>  
      <th>Summary</th>  
      <th>Stard date</th>  
      <th>End date</th>  
    </tr>  
  </thead>  
  <tbody>  

    <!-- @tasks is passed from controller to view -->  
    <% @projects.each do |project| %>           <!-- for loop -->  
    <tr>  
      <td><%= project.id %></td>           <!--get Project ID using reference -->  
      <td><%= project.name %></td>         <!--get Project title -->  
      <td><%= project.summary %></td>      <!--get Project summary --> 
      <td><%= project.start_date %></td>   <!--get Project start date --> 
      <td><%= project.end_date %></td>     <!--get Project end date -->  
      <td><%= link_to 'Edit project', edit_project_path(project) %></td>  
      <td><%= link_to 'Delete project', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>  
    </tr>  
    <% end %>  
  </tbody>  
</table>
<%= link_to 'New Project', new_project_path %>
<br>  
<h2>Tasks</h2>
<table>  
  <thead>  
    <tr>  
      <th>Task id</th>  
      <th>Name of project</th>  
      <th>Title</th>
      <th>Description</th>    
      <th>Status</th>    
    </tr>  
  </thead>  
  <tbody>  
    <!-- @tasks is passed from controller to view -->  
    <% @tasks.each do |task| %>           <!-- for loop -->  
    <tr>  
      <td><%= task.id %></td>         	<!--get Project ID using reference -->  
      <td><%= task.project.name %></td>      		<!--get Project name -->  
      <td><%= task.title %></td>								<!--get Task Title --> 
      <td><%= task.description %></td>					<!--get Task Description --> 
      <td><%= task.status %></td>								<!--get Task Status -->  
      <td><%= link_to 'Edit task', edit_task_path(task) %></td>  
      <td><%= link_to 'Delete task', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>  
    </tr>  
    <% end %>  
  </tbody>  
</table>
<%= link_to 'New Task', new_task_path %>
<br>  
<h2>Users</h2>
<table>  
  <thead>  
    <tr>   
      <th>Name of project</th>  
      <th>Title of task</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Password</th>
      <th>Email</th>
      <th>Admin</th>
    </tr>  
  </thead>  
  <tbody>  
    <!-- @tasks is passed from controller to view -->  
    <% @users.each do |user| %>           <!-- for loop -->  
    <tr>
      <td><%= user.task.project.name %></td>        <!--get Project Name -->  
      <td><%= user.task.title %></td>               <!--get Task Title --> 
      <td><%= user.first_name %></td>               <!--get User First_name -->  
      <td><%= user.last_name %></td>                <!--get User Last_name -->  
      <td><%= user.password %></td>                 <!--get User password --> 
      <td><%= user.email %></td>                    <!--get User email --> 
      <td><%= user.admin %></td>                    <!--get User admin or not -->  
      <td><%= link_to 'Edit user', edit_user_path(user) %></td>  
      <td><%= link_to 'Delete user', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>  
    </tr>  
    <% end %>  
  </tbody>  
</table>
<%= link_to 'New User', new_user_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', more_info_url %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @project.summary %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @project.end_date %>
</p>
  <strong>Project id:</strong>
  <%= @project.id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', more_info_url %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br>
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
    <br>
  </div>

  <div class="field">
    <br>
    <%= form.label :description %>
    <br>
    <%= form.text_area :description %>
    <br>
  </div>

  <div class="field">
    <br>
    <%= form.label :status %>
    <br>
    <%= form.select(:status, options_for_select([['New'], ['In progress'], ['Done']]) )%>
    <br>
  </div>

  <div class="field">
    <br>
    <%= form.label :project_id %>
    <br>
    <%= form.text_field :project_id %>
    <br>
  </div>

  <div class="actions">
    <br>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', more_info_url %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= task.project %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', more_info_url %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Task id:</strong>
  <%= @task.id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', more_info_url %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <br>
    <%= form.text_field :first_name %>
    <br>
  </div>

  <div class="field">
    <br>
    <%= form.label :last_name %>
    <br>
    <%= form.text_field :last_name %>
    <br>
  </div>

  <div class="field">
    <br>
    <%= form.label :email %>
    <br>
    <%= form.text_field :email %>
    <br>
  </div>

  <div class="field">
    <br>
    <%= form.label :password %>
    <br>
    <%= form.text_field :password %>
    <br>
  </div>

  <div class="field">
    <br>
    <%= form.label :admin %>
    <br>
    <%= form.check_box :admin %>
    <br>
  </div>

  <div class="field">
    <br>
    <%= form.label :task_id %>
    <br>
    <%= form.text_field :task_id %>
    <br>
  </div>

  <div class="actions">
    <br>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', more_info_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Admin</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.admin %></td>
        <td><%= user.task %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', more_info_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', more_info_path %>